import path from "node:path";
import fs from "node:fs";
import { fileURLToPath } from "node:url";
import renderRulesTableContent from "./render-rules.ts";

// -----------------------------------------------------------------------------
const readmeFilePath = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  "../docs/rules/index.md",
);
fs.writeFileSync(
  readmeFilePath,
  `---
sidebarDepth: 0
---

# Available Rules

<!-- This file is automatically generated in tools/update-docs-rules-index.js, do not change! -->
${renderRulesTableContent()}`,
);
