import path from "path";
import fs from "fs";
import renderRulesTableContent from "./render-rules";

// -----------------------------------------------------------------------------
const readmeFilePath = path.resolve(__dirname, "../docs/rules/README.md");
fs.writeFileSync(
  readmeFilePath,
  `---
sidebarDepth: 0
---

# Available Rules

<!-- This file is automatically generated in tools/update-docs-rules-index.js, do not change! -->
${renderRulesTableContent()}`
);
